version: "2.1"
services:
  rdesktop:
    image: donswanson/rdesktop
    container_name: rdesktop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock #optional
      - ./rdesktop:/config #optional

    ports:
      - 33389:3389
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped

